
version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package \
         --template-file SAM_template.yaml \
         --s3-bucket iti-products \
         --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
